\section{Async await}
Bei einer \textbf{async} Funktion handelt es sich um eine Funktion, die dank einer Eventschleife asynchron operiert. In einer Eventschleife werden auf Events gewartet bis diese auftreten. Innerhalb dieser Funktion wird implizit ein Promise genutzt. Die Stärke von async ist die Syntax und der strukturelle Aufbau einer solchen asynchronen Operation. Diese lässt den Code synchron aussehen.\cite{async-await} Ein einfaches Beispiel:

\begin{figure}[H]
\begin{lstlisting}[basicstyle=\small]
function hello() {
    return 'world';
}
\end{lstlisting}
\caption{Funktion gibt explizit und implizit ein string zurück.}
\end{figure}

\begin{figure}[H]
\begin{lstlisting}[basicstyle=\small]
async function hello() {
    return 'world';
}
\end{lstlisting}
\caption{Funktion gibt explizit ein string und implizit ein Promise\textless string\textgreater zurück.}
\end{figure}

\noindent
Der async Ausdruck an einer Funktion wandelt den Rückgabetyp T in ein Promise\textless T\textgreater um. Um explizit und implizit ein Promise\textless string\textgreater zu verwenden, könnte man beispielsweise ein Promise.resolve('world') ausliefern. Eine asynchrone Funktion kann zudem einen \textbf{await} Ausdruck enthalten. Dies lässt die asynchrone Funktion pausieren bis der übergebene Promise eingetroffen ist. Daraufhin wird die Ausführung der Funktion mit dem zurückgegeben Wert des Promise fortgesetzt. Ein await ist nur innerhalb einer async Funktion valide einsetzbar. Ein einfaches Beispiel zum Verständnis:\\

\subsubsection{Funktionsweise}

\noindent
Vor dem Ausführen des Beispiels sollte wieder die introduction.ts als Eingangsdatei in der webpack.config.js definiert werden.

\begin{figure}[H]
\begin{lstlisting}[basicstyle=\small]
const keepsHisWord = true;
const resolveRightAway = new Promise((resolve, reject) => {
    if (keepsHisWord) {
        resolve('Promises kept!');
    } else {
        reject('Promise NOT kept!');
    }
});

async function getHisWord() {
    const keptWord = await resolveRightAway;
    console.log('Jack, ' + keptWord);
}

getHisWord();
\end{lstlisting}
\end{figure}

\noindent
In diesem Code-Block wird das erste Promise Beispiel genutzt. Wie man nun sehen kann wird an dem await Ausdruck eine Konstante gebildet um den Promise-Wert, der zurückgegeben wird, weiterzunutzen. Man muss nicht mehr mit der then()-Methode den Promise entpacken, um auf den Wert des Promise-Objekts zuzugreifen. Async await greift direkt auf den Wert zu. Nun kann man sich fragen: Was passiert wenn ein Promise fehlschlägt? Wie bekommt man den Wert des Promise-Objekts bei einem Fehlschlag? \\

\noindent
Ähnlich wie bei Java oder Swift gibt es auch in Javascript ein \textbf{try-catch}-Block. Wenn ein Promise fehlschlägt, wird eine Exception geworfen.\cite{async-await-heise} Diese kann daraufhin mit dem catch-Block gefangen werden. Code-technisch würde dies so aussehen:

\begin{figure}[H]
\begin{lstlisting}[basicstyle=\small]
const rejectedPromise = Promise.reject('I reject on purpose');

async function getNotHisWord() {
    try {
        const keepNotHisWord = await rejectedPromise;
        console.log(keepNotHisWord);
    } catch (e) {
        console.log('Jack said: ' + e);
    }
}

getNotHisWord();
\end{lstlisting}
\caption{Die Konsole wird niemals keepNotHisWord ausgeben, da innerhalb des await Konstrukts eine Exception geworfen wird.}
\end{figure}

\noindent
Dabei wird der Code syntaktisch so geschrieben, als würde dieser synchron ausgeführt werden. Dies führt zu einer erheblichen Steigerung der Lesbarkeit und verhindert Verschachtelungen wie man sie oben gesehen hat (siehe Abb. 17). Um auf das ursprüngliche Beispiel mit der Promise-Verkettung zurückzukommen, würde der Code mit async-await so aussehen:\\

\noindent
Vor dem Ausführen des Beispiels sollte wieder die stories.ts als Eingangsdatei in der webpack.config.js definiert werden.

\begin{figure}[H]
\begin{lstlisting}[basicstyle=\small]
async function getFirstSections() {
    try {
        for (const n of [1, 2, 3]) {
            story.spawn(await story.getChapter(n));
        }
    } finally {
        story.spinnerElement.style.display = 'none';
        story.displayFinished();
    }
}

getFirstSections();
\end{lstlisting}
\caption{Die Methode verhält sich genau so wie in Abb. 17}
\end{figure}

\noindent
Ohne jeglicher Verkettung wird mit dem await Konstrukt auf die Promise Auflösung gewartet und der entstandene Wert als Parameter in der Methode spawn() übergeben. Daraufhin wird weiter in der Schleife iteriert. Zudem bietet der try-catch-Block auch finally an. Ähnlich wie bei der Promise-Prototyp Methode wird unabhängig vom Ausgang des try-catch-Blocks in dem finally-Block vorrangeschreitet.

\subsubsection{Einsetzen wenn sinnvoll}

Beim Einsetzen von async await muss sich vor Augen geführt werden, wann ein Einsatz als solches Sinn ergibt. Kommt man wieder zum Anwendungsfall, man möchte die ersten fünf Kapitel parallel in die DOM laden, würde der Code hierfür so aussehen:

\begin{figure}[H]
\begin{lstlisting}[basicstyle=\small]
async function getFirstSectionsInParallel() {
    try {
        const promises = [];

        [1, 2, 3].forEach(n => 
        promises.push(story.getChapter(n)));

        story.spawn(await Promise.all(promises));
    } finally {
        story.spinnerElement.style.display = 'none';
        story.displayFinished();
    }
}

getFirstSectionsInParallel();
\end{lstlisting}
\end{figure}

\noindent
Wie man sehen kann gibt es keinen großen Mehrwert innerhalb der async await Exekution im Vergleich zur Abbildung 18. Die einzigen Abhängigkeiten bestehen zwischen story.getChapter() und story.spawn(). Es können erst dann Kapitel in die DOM geladen werden, sobald die Daten von der API ankommen. Beim übergeben der Promises in einem Array sind alle im pending Zustand. Erst mit await Promise.all(iterable) wird parallel auf die Auflösung gewartet. Die Stärke von async await kommt erst dann zur Geltung, wenn asynchrone Operationen sequentiell ausgeführt werden müssen. Als Faustregel kann festgelegt werden, dass Funktionen mit dem Präfix \textbf{async} ein Promise-Objekt zurückgeben. Selbst wenn explizit ein primitiver Typ zurückgegeben wird, stellt async sicher, dass dieser Typ in ein Promise ist. \textbf{Await} pausiert die Ausführung einer asynchronen Funktion, bis die blockierende Aktion eingetroffen ist. Dabei können mehrere awaits innerhalb einer async Funktion definiert werden. Um Fehlschläge zu fangen sollte Javascripts \textbf{try-catch}-Block angewendet werden. Es sollte unterschieden werden, ob der Code sequentiell oder parallel ausgeführt werden soll. Möchte man mehrere Promises parallel ausführen, können diese als Array in einem Promise.all() übergeben werden.